--- 
abstract: Template::Alloy (TT) View Class
author: Carl Franks, C<cfranks@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-View-TT-Alloy
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Catalyst: 5.7
  Class::Accessor: 0
  NEXT: 0
  Path::Class: 0
  Task::Weaken: 0
  Template::Alloy: 0
version: 0.00001
