---
abstract: 'Template::Alloy (TT) View Class'
author:
  - 'Carl Franks, C<cfranks@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.97'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-TT-Alloy
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Catalyst: 5.7
  Class::Accessor: 0
  Path::Class: 0
  Task::Weaken: 0
  Template::Alloy: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.00003
