---
abstract: 'Template::Alloy (TT) View Class'
author:
  - 'Dean Hamstead <dean@bytefoundry.com.au>'
build_requires:
  Catalyst::Test: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-View-Alloy
requires:
  Carp: '0'
  Catalyst: '5.7'
  Class::Accessor: '0'
  Path::Class: '0'
  Task::Weaken: '0'
  Template::Alloy: '0'
resources:
  homepage: https://github.com/djzort/Catalyst-View-TT-Alloy
  repository: https://github.com/djzort/Catalyst-View-TT-Alloy.git
version: '0.00004'
